os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_REFERENCE="Assimp/1.3.3"
    - CONAN_USERNAME="jacmoe"
    - CONAN_CHANNEL="testing"

matrix:
   include:
      - os: linux
        services:
          - docker
        sudo: required
        language: python
        env: CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1
      - os: linux
        services:
          - docker
        sudo: required
        language: python
        env: CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1
      - os: linux
        services:
          - docker
        sudo: required
        language: python
        env: CONAN_GCC_VERSIONS=6.3 CONAN_USE_DOCKER=1   
      #- os: osx 
      #  osx_image: xcode8.3 # apple-clang 8.1
      #  language: generic
      #  env: CONAN_APPLE_CLANG_VERSIONS=8.1 # CONAN_CURRENT_PAGE=apple-clang_81   
      #- os: osx 
      #  osx_image: xcode8.2  # apple-clang 8.0
      #  language: generic
      #  env: CONAN_APPLE_CLANG_VERSIONS=8.0 # CONAN_CURRENT_PAGE=apple-clang_80    

before_install:
 - chmod +x ./.travis/install.sh
 - chmod +x ./.travis/run.sh

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
