build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    #CONAN_UPLOAD: https://api.bintray.com/conan/jacmoe/Conan
    CONAN_REFERENCE: "Assimp/3.3.1"
    CONAN_USERNAME: "jacmoe"
    CONAN_CHANNEL: "stable"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_TOTAL_PAGES: 1

    matrix:
        #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        #  CONAN_VISUAL_VERSIONS: 15
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        #  CONAN_VISUAL_VERSIONS: 12

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - pip.exe install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory

test_script:
  - python build.py
